### ISSUE TITLE
创建新的标注项目时出错The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/PaddleLabel-Frontend#41]
在启动pplabel和pplabel_ml之后，新建一个新的分割项目会报错，只有先把pplabel_ml关掉，然后创建完项目再启动pplabel_ml才能创建成功

**Comment by linhandev** [comment]
能确定这两个相关吗，这个报错应该是交互式分割检测后端没找到的报错，不应该影响项目创建。我这进入分割标注也有这个报错但是创建项目是没问题的
